use_gpu: true
exp_name: ~

dataset: cifar10  # cifar10 / cifar100
dataroot: ../data

epochs: 160
batch_size: 256

model: cbam_resnet18

optimizer:
  choice: sgd
  sgd:
    lr: 0.1
    weight_decay: 0.0005
    momentum: 0.9
  adam:
    lr: 0.1

scheduler:
  choice: cosineannealinglr
  cosineannealinglr:
    eta_min: 0.001
  multisteplr:
    gamma: 0.1
    milestones: [80, 120]

save_per_epochs: 20
resume_path: ~
