dataset: cifar10  # cifar10 / cifar100
dataroot: /home/jason/data

epochs: 200
batch_size: 256

model: vit_small

optimizer:
  choice: adam
  sgd:
    lr: 0.001
    weight_decay: 0.0005
    momentum: 0.9
  adam:
    lr: 0.001
    weight_decay: 0.00005

scheduler:
  choice: cosineannealinglr
  cosineannealinglr:
    eta_min: 0.00001
  multisteplr:
    gamma: 0.1
    milestones: [80, 120]

save_freq: 20

resume:
  log_root: ~
  ckpt_path: ~
