dataset: cifar10  # cifar10 / cifar100
dataroot: /home/jason/data

epochs: 160
batch_size: 256

model: resnet18

optimizer:
  choice: sgd
  sgd:
    lr: 0.1
    weight_decay: 0.0005
    momentum: 0.9
  adam:
    lr: 0.1
    weight_decay: 0.0005

scheduler:
  choice: cosineannealinglr
  cosineannealinglr:
    T_max: 160
    eta_min: 0.001
  multisteplr:
    gamma: 0.1
    milestones: [80, 120]
  warmup:
    warmup_epochs: 0
    warmup_factor: 0.01

save_freq: 20

resume:
  log_root: ~
  ckpt_path: ~
